version: '3.8'

services:
  gemini-stacktrace-dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace
      - vscode_server:/home/vscode/.vscode-server
      - ~/.gitconfig:/home/vscode/.gitconfig:ro
    user: vscode
    environment:
      - GEMINI_API_KEY
    command: sleep infinity
    container_name: gemini-stacktrace-dev

volumes:
  vscode_server:
    name: vscode_server
